# Generated by Django 5.2.8 on 2025-11-28 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cuestionario_alter_diarioemocional_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEmocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emocion', models.CharField(choices=[('FELIZ', 'Feliz'), ('TRANQUILO', 'Tranquilo'), ('NEUTRAL', 'Neutral'), ('ANSIOSO', 'Ansioso'), ('TRISTE', 'Triste'), ('ENOJADO', 'Enojado')], max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_emocionales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Emoción',
                'verbose_name_plural': 'Registros de Emociones',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
