# Generated by Django 5.2.8 on 2025-11-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_registroemocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionario',
            name='tiempo_estimado',
            field=models.CharField(default='5 min', max_length=50),
        ),
        migrations.AddField(
            model_name='diarioemocional',
            name='titulo',
            field=models.CharField(default='Sin título', max_length=200),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tipo_pregunta',
            field=models.CharField(choices=[('ESCALA', 'Escala 1-10 (Slider)'), ('SELECCION', 'Selección Única (Botones)'), ('BOOLEAN', 'Sí/No'), ('TEXTO', 'Texto Libre')], default='SELECCION', max_length=20),
        ),
    ]
