# Generated by Django 5.2.8 on 2025-11-29 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cuestionario_tiempo_estimado_diarioemocional_titulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(help_text='Descripción corta para la tarjeta', max_length=300)),
                ('categoria', models.CharField(choices=[('RESPIRACION', 'Respiración'), ('RELAJACION', 'Relajación'), ('MINDFULNESS', 'Mindfulness'), ('MOVIMIENTO', 'Movimiento')], max_length=20)),
                ('icono', models.CharField(choices=[('VIENTO', 'Viento (Respiración)'), ('CORAZON', 'Corazón (Relajación)'), ('LUNA', 'Luna (Noche/Mindfulness)'), ('SOL', 'Sol (Día/Gratitud)')], default='VIENTO', max_length=20)),
                ('duracion', models.IntegerField(help_text='Duración en minutos')),
                ('instrucciones', models.TextField()),
                ('media_url', models.URLField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EjercicioCompletado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ejercicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_completados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_completado'],
            },
        ),
    ]
