# Generated by Django 5.2.8 on 2025-11-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_publicacion_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.TextField(help_text='Breve descripción para la tarjeta', max_length=300)),
                ('contenido', models.TextField()),
                ('categoria', models.CharField(choices=[('ANSIEDAD', 'Ansiedad'), ('ESTRES', 'Estrés'), ('SUENO', 'Sueño'), ('RELACIONES', 'Relaciones'), ('AUTOCUIDADO', 'Autocuidado'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('imagen_url', models.URLField(blank=True, help_text='URL de la imagen de portada', null=True)),
                ('tiempo_lectura', models.CharField(default='5 min', max_length=20)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Artículo Psicoeducativo',
                'verbose_name_plural': 'Artículos Psicoeducativos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
