# Generated by Django 5.2.8 on 2025-11-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_articulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField(help_text='Consejo breve (máx 2-3 líneas)')),
                ('categoria', models.CharField(choices=[('DIARIO', 'Diario'), ('ESTRES', 'Estrés'), ('SUENO', 'Sueño'), ('BIENESTAR', 'Bienestar')], default='BIENESTAR', max_length=20)),
                ('es_destacado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tip de Bienestar',
                'verbose_name_plural': 'Tips de Bienestar',
            },
        ),
    ]
