# Generated by Django 5.2.8 on 2025-12-05 03:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroemocion',
            name='intensidad',
            field=models.IntegerField(default=5, help_text='Nivel de intensidad de la emoción (escala numérica)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='registroemocion',
            name='nota',
            field=models.TextField(blank=True, help_text='Nota privada opcional sobre la emoción', null=True),
        ),
    ]
